#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */

/*
/  Putting this in both ravg.c and avg_proc.c
/     Usage : ./ravg 127.0.0.1 1 0 2 3 4 5 2
/        -This will sort the array in descending order.
/     Usage : ./ravg 127.0.0.1 0 0 2 3 4 5 2
/        -This will sort the array in ascending order
/     The first element of the array of numbers found after the ip address is the flag (i.e. 1 is DESCENDING 
/        and 0 is ASCENDING). It gets stored in the values of the input_data struct, 
/        and it is skipped when the program sorts the input values. 
/        This program sorts in descending order by default. 
*/

//comparator for ascending qsort
int a_comp(const void* a, const void* b){
  if((*(double*) a) - (*(double*) b) > 0)
    return 1;
  else return 0;
}
//comparator for descending qsort
int d_comp(const void* a, const void* b){
  if((*(double*) b) - (*(double*) a) > 0)
    return 1;
  else return 0;
}


/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */


input_data * average_1(input_data *input, CLIENT *client) 
  {
    /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */


    //dp holds the input values that are found in the input_data struct
    double *dp = input->input_data.input_data_val;
    //loop control variable
    int i;
  
  //holds size value
  int n = input->input_data.input_data_len;
  //holds the sort flag to differentiate between a and d (0 or 1);
  int v = dp[0];
  //skips the flag while sorting
  dp++;
  
  if(v == 0){
    //sorts in ascending
    qsort(dp--, n-1, sizeof(double), a_comp);
  }
  else if(v == 1){
    //sorts in descending
    qsort(dp--, n-1, sizeof(double), d_comp);
  }
  //repopulates the input_data struct with the sorted array to be returned
  for(int i = 1; i < n; i++){
    input->input_data.input_data_val[i] = dp[i];
  }


  return( input );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
