#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
double median = 0;
//comparator for qsort
int comp(const void* a, const void* b){
 if (*(double*) a - *(double*) b > 0){
   return 1;
 }
 else if(*(double*) a - *(double*) b < 0){
   return -1;
 }
 else 
    return 0;
}
/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
double * average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  int n = input->input_data.input_data_len;

  //sort array
  qsort(dp, n, sizeof(double), comp);
    
    // if number of elements are even
    if(n % 2 == 0){
      double d = dp[(n-1)/2];
      double f = dp[n/2];
      median = (d+f)/2.0;
  }
    // if number of elements are odd
    else
        median = dp[n/2];
    
    return &median;
}


/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
